/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Dependency: typeof import('./src/components/Dependency/Dependency.vue')['default']
    Dependency_Graphviz: typeof import('./src/components/Dependency/Dependency_Graphviz.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FunctionAreas: typeof import('./src/components/FunctionAreas/FunctionAreas.vue')['default']
    IEpCaretLeft: typeof import('~icons/ep/caret-left')['default']
    IEpCaretRight: typeof import('~icons/ep/caret-right')['default']
    IEpLink: typeof import('~icons/ep/link')['default']
    InfoList: typeof import('./src/components/InfoList/InfoList.vue')['default']
    ModuleDetail: typeof import('./src/components/InfoList/cpns/ModuleDetail.vue')['default']
    Overview: typeof import('./src/components/InfoList/cpns/Overview.vue')['default']
    SizeBar: typeof import('./src/components/PackageInfo/SizeBar.vue')['default']
  }
}
