/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    D: typeof import('./src/components/Dependency/D.vue')['default']
    Depdency: typeof import('./src/components/Dependency/Depdency.vue')['default']
    Dependency: typeof import('./src/components/Dependency/Dependency.vue')['default']
    Dependency_Graphviz: typeof import('./src/components/Dependency/Dependency_Graphviz.vue')['default']
    Dependency_Toggle: typeof import('./src/components/Dependency/Dependency_Toggle.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    FunctionAreas: typeof import('./src/components/FunctionAreas/FunctionAreas.vue')['default']
    Graph: typeof import('./src/components/Dependency/Graph.vue')['default']
    Header: typeof import('./src/components/Header/Header.vue')['default']
    InfoList: typeof import('./src/components/InfoList/InfoList.vue')['default']
  }
}
