/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Dependency: typeof import('./components/Dependency/Dependency.vue')['default']
    Dependency_Graphviz: typeof import('./components/Dependency/Dependency_Graphviz.vue')['default']
    Dependency_Toggle: typeof import('./components/Dependency/Dependency_Toggle.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    FunctionAreas: typeof import('./components/FunctionAreas/FunctionAreas.vue')['default']
    Header: typeof import('./components/Header/Header.vue')['default']
    InfoList: typeof import('./components/InfoList/InfoList.vue')['default']
  }
}
